theme: jekyll-theme-minimal
show_downloads: ["false"]
logo: /assets/imgs/logo.png
title: A Developer's Guide to Building and Testing Accessible Mobile Apps
tsdllogo: /assets/imgs/horizontalLightBrackgrounds.png

navigation:
  - title: Video
    link: /video.hmtl
